/*
 * << Crazy Copter >>
 * 
 * Created by Team 11
 * ------------------
 *   Brandon Banks
 *    Quang Tran
 *    Noah Sauls
 *    Peter Graef
 * ------------------
 * CS 321 - Rochowiak
 * ------------------
 * Overview:
 *   Basic side scroler game in JAVA
 *	 Try to avoid oncoming eneimes on screen to survive
 *   Click on options to load/save/modify player profile
 *
 * Controls (In-Game):
 *   SPACEBAR  - jump
 *   A         - move left
 *   D         - move right
 *   LeftClick - pause/resume
 *
 */
package CrazyCopter.Forms;

import CrazyCopter.Database.PlayerProfile;
import CrazyCopter.Game;
import java.util.Set;

/**
 * Options form using Netbeans' built in form builder
 * @author Team 11
 */
public class Options_Form extends javax.swing.JFrame {

    /**
     * Creates a PlayerProfile and will modify based on user selection(s) on the form
     */
    private PlayerProfile player = new PlayerProfile("Player 1");
    
    /**
     * Creates new form Options_Form
     */
    public Options_Form() {
        initComponents();
        this.Player_Name.setText("[ enter new name here ]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerSelection = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        HelicopterColorChoice = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Player_Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayerSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player 1", "Quang", "Brandon", "Noah", "Peter" }));
        PlayerSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PlayerSelectionItemStateChanged(evt);
            }
        });
        PlayerSelection.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PlayerSelectionPropertyChange(evt);
            }
        });

        jButton1.setText("Add Player");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HelicopterColorChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Blue", "Red", "Yellow" }));
        HelicopterColorChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelicopterColorChoiceActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Player_Name.setText("[ enter new name here ]");
        Player_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Player_NameMouseClicked(evt);
            }
        });
        Player_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_NameActionPerformed(evt);
            }
        });
        Player_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Player_NameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Player_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(HelicopterColorChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HelicopterColorChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelicopterColorChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelicopterColorChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelicopterColorChoiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // close form
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String helicopterChoice = this.HelicopterColorChoice.getSelectedItem().toString();
        int helicopter = 0;
        
        switch(helicopterChoice)
        {
            case "Green":  helicopter = 1; break;
            case "Blue":   helicopter = 2; break;
            case "Red":    helicopter = 3; break;
            case "Yellow": helicopter = 4; break;
        }

        player.setName(this.PlayerSelection.getSelectedItem().toString());
        player.setHelicopter(helicopter); // update helicopter choice
        System.out.println(player.getName() + "  " + player.getHelicopter() + "  " +  player.getScore());
        
        player.saveProfile();

        Game.getInstance().setPlayer(player);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Player_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_NameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Player_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.PlayerSelection.addItem(this.Player_Name.getText());
        this.PlayerSelection.setSelectedIndex(this.PlayerSelection.getItemCount()-1);
        this.Player_Name.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Player_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player_NameKeyPressed
        // TODO add your handling code here:
                

    }//GEN-LAST:event_Player_NameKeyPressed

    private void Player_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Player_NameMouseClicked
        // TODO add your handling code here:
        if(this.Player_Name.getText().equalsIgnoreCase("[ enter new name here ]"))
        {
           this.Player_Name.setText("");
        }
    }//GEN-LAST:event_Player_NameMouseClicked

    private void PlayerSelectionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PlayerSelectionPropertyChange
        // TODO add your handling code here:
 
    }//GEN-LAST:event_PlayerSelectionPropertyChange

    private void PlayerSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PlayerSelectionItemStateChanged
        // TODO add your handling code here:
       ////////////////////////////////////////////
        player.setName(PlayerSelection.getSelectedItem().toString());
        // player.loadProfile();
        // System.out.println(player.getHelicopter());
        // System.out.println(player.getName());
    }//GEN-LAST:event_PlayerSelectionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HelicopterColorChoice;
    private javax.swing.JComboBox<String> PlayerSelection;
    private javax.swing.JTextField Player_Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
